import React from 'react';
import {View, Text} from 'react-native';
import MainCart from './src/Screens/Cart/MainCart';
import Main from './src/Screens/HavaUseBemo/Main';
import MainScreen2 from './src/Screens/Main/MainScreen2';
import Dispensaries from './src/Screens/Dispensaries/Dispensaries';
import MyReturnAndRefund from './src/Screens/ReturnAndRefund/MyReturnAndRefund';
import MyProfile from './src/Screens/Profile/MyProfile';
// import DetailsReview from './src/Screens/Details/DetailsReview';
import SettingScreen from './src/Screens/SettingScreen/SettingScreen';
import BuynowScreen from './src/Screens/BuyNow/BuynowScreen';
import Main3 from './src/Screens/Main/MainScreen';
import Payment from './src/Screens/CheckOut/Payment';
import Timing from './src/Screens/Timing/Timing';
import HavausePlusMaps from './src/Screens/Maps/HavausePlusMaps';
import RateApp from './src/Screens/Profile/RateApp';
import PaymentMethod from './src/Screens/Payment/PaymentMethod';
import SelectCountry from './src/Screens/SelectCountry';
import SelectCurrency from './src/Screens/SelectCurrency';
import EditProfile from './src/Screens/EditProfile';
import SellerDetails from './src/Screens/SellerDetails/Main';
import Cash from './src/Screens/Cash';
import AddPaymentMethod from './src/Screens/AddPaymentMethod';
import ShippingMethod from './src/Screens/ShippingMethod';
import ProductList from './src/Screens/ProductList';
import Orders from './src/Screens/Orders';
import RefundRequest1 from './src/popups/RefundRequest';
import OrderDetails from './src/popups/OrderDetails';
import ProductDetail from './src/Screens/ProductDetail';
import Login from './src/Screens/Login';
import Filter from './src/popups/Filter';
import TrackOrderDelivered from './src/Screens/TrackOrder';
import Continue from './src/Screens/Continue';
import Navigation from './src/navigation';
import ScanPakages from './src/Screens/ScanPakages';
import Request from './src/popups/RefundRequest';
import Notifyme from './src/popups/Notifyme';
import OrderComplete from './src/popups/OrderComplete';
import SearchTag from './src/popups/SearchTag';
import VenderRegistraion from './src/Screens/VenderRegistration';
import RefundItem from './src/Screens/ReturnAndRefund/RefundItem';
import RefundRequest from './src/Screens/ReturnAndRefund/RefundRequest';
import Photo from './src/Screens/Photo';
import PaymentInformation from './src/popups/PaymentInformation';
import OrderStatus from './src/Screens/OrderStatus/OrderStatus';
import SelfieCamera from './src/Screens/SelfieCamera';
import IdCamera from './src/Screens/IDCamera';
import PlusVerification from './src/Screens/PlusVerification';
import PrivacyAndPolicy from './src/Screens/AboutAndTerms/PrivacyAndPolicy';
import AboutUS from './src/Screens/AboutAndTerms/AboutUs';
import ContactSupport from './src/Screens/ContactSupport';
import ViewAll from './src/Screens/ViewAll';
import ChatScreen from './src/Screens/ChatScreen';
import WelcomeScreen from './src/Screens/WelcomeScreen';
import RateExperince from './src/popups/RateExperince';

export default function App() {
  return <Navigation />;
}
